// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./src/components/Breadcrumb.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    // IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    // IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    // IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    // IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    // IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LeftTree: typeof import('./src/components/LeftTree.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
